set number
set relativenumber
set tabstop=2
set grepprg=ag\ --nogroup\ --nocolor

syntax enable

colorscheme monokai

:nnoremap <C-B> :CtrlPDir<CR>
:nnoremap <C-f> :Ack 

let g:ackprg = 'ag --nogroup --nocolor --column'
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

call plug#begin('~/.vim/plugged')

Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'kchmck/vim-coffee-script'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'mileszs/ack.vim'


call plug#end()
