set number
set relativenumber
set tabstop=2

if executable('ag')
	set grepprg=ag\ --nogroup\ --nocolor
	let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
	let g:ctrlp_use_caching = 0

	command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
endif

syntax enable

:nnoremap <C-B> :CtrlPDir<CR>
:nnoremap <C-f> :Ag

let g:ackprg = 'ag --nogroup --nocolor --column'
let g:ctrlp_max_files = 0
let g:ctrlp_max_depth = 40

call plug#begin('~/.vim/plugged')

Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'kchmck/vim-coffee-script'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'mileszs/ack.vim'


call plug#end()
